plugins {
    id 'com.android.application' version '8.1.0' apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

subprojects {
    version = '1.0-SNAPSHOT'
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << "-Xlint:all"
    }
}
