package com.e2eechat.core.keys;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.KeyPair;
import java.security.SecureRandom;
import java.security.Signature;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.TimeZone;

/**
 * Builds the self-signed certificate that lets an identity key be stored in a PKCS#12 keystore.
 *
 * <p>The certificate carries no trust and is never presented to anyone. PKCS#12 will not hold a
 * private key without a certificate chain, and that is the only reason one exists: identity in
 * this protocol is the SHA-256 of the public key (see {@code PeerId}), not anything an X.509
 * field says.
 *
 * <p><strong>Why this is hand-rolled.</strong> Identity keys used to be generated by running
 * {@code keytool} in a subprocess. That put the user's passphrase in the process argument list,
 * where any other process running as the same user can read it, and it made key generation depend
 * on a JDK tool that a packaged build does not ship - the jpackage app image contains one
 * executable, and it is not keytool. Generating in-process fixes both, and the JDK offers no
 * public API for making a certificate, so the structure is encoded here. It is deliberately the
 * smallest certificate that parses: X.509 v1, one CN, SHA-256 with RSA.
 */
public final class SelfSignedCertificate {

    /** OID 2.5.4.3, the common name attribute. */
    private static final byte[] OID_COMMON_NAME = {0x55, 0x04, 0x03};

    /** OID 1.2.840.113549.1.1.11, sha256WithRSAEncryption. */
    private static final byte[] OID_SHA256_WITH_RSA = {
        0x2A, (byte) 0x86, 0x48, (byte) 0x86, (byte) 0xF7, 0x0D, 0x01, 0x01, 0x0B,
    };

    private static final String SIGNATURE_ALGORITHM = "SHA256withRSA";

    /** Ten years. The certificate is a container, so expiry has no security meaning here. */
    private static final int VALIDITY_DAYS = 3650;

    private static final long MILLIS_PER_DAY = 24L * 60 * 60 * 1000;

    /** Shared because SecureRandom is thread-safe and seeding it per call buys nothing. */
    private static final SecureRandom RANDOM = new SecureRandom();

    private SelfSignedCertificate() {
    }

    /**
     * Issues a certificate over {@code keyPair}, signed by its own private key.
     *
     * @param keyPair the identity key the certificate wraps
     * @param commonName the CN to place in the subject and issuer
     */
    public static X509Certificate generate(KeyPair keyPair, String commonName) throws Exception {
        Date notBefore = new Date();
        Date notAfter = new Date(notBefore.getTime() + VALIDITY_DAYS * MILLIS_PER_DAY);

        byte[] tbsCertificate = encodeTbsCertificate(
                keyPair.getPublic().getEncoded(), commonName, notBefore, notAfter);

        Signature signer = Signature.getInstance(SIGNATURE_ALGORITHM);
        signer.initSign(keyPair.getPrivate());
        signer.update(tbsCertificate);
        byte[] signature = signer.sign();

        byte[] certificate = sequence(
                tbsCertificate,
                signatureAlgorithm(),
                bitString(signature));

        // Parsed back rather than returned as bytes, so a malformed encoding fails here at
        // generation rather than later when something tries to read the keystore.
        return (X509Certificate) CertificateFactory.getInstance("X.509")
                .generateCertificate(new java.io.ByteArrayInputStream(certificate));
    }

    /**
     * The signed half of the certificate.
     *
     * <p>Version 1, which is the version whose field is simply absent. A v3 certificate would need
     * an extensions block this has no use for.
     */
    private static byte[] encodeTbsCertificate(byte[] subjectPublicKeyInfo, String commonName,
                                               Date notBefore, Date notAfter) throws IOException {
        byte[] issuerAndSubject = name(commonName);
        return sequence(
                serialNumber(),
                signatureAlgorithm(),
                issuerAndSubject,
                validity(notBefore, notAfter),
                // Self-signed, so the subject is the issuer.
                issuerAndSubject,
                // An encoded public key is already a DER SubjectPublicKeyInfo.
                subjectPublicKeyInfo);
    }

    /** A positive random serial. Uniqueness matters to nothing here, but zero is malformed. */
    private static byte[] serialNumber() throws IOException {
        byte[] bytes = new byte[8];
        RANDOM.nextBytes(bytes);
        BigInteger serial = new BigInteger(1, bytes).add(BigInteger.ONE);
        return tagged(0x02, serial.toByteArray());
    }

    private static byte[] signatureAlgorithm() throws IOException {
        return sequence(tagged(0x06, OID_SHA256_WITH_RSA), tagged(0x05, new byte[0]));
    }

    /** {@code SEQUENCE OF SET OF SEQUENCE { OID, value }}, holding one CN. */
    private static byte[] name(String commonName) throws IOException {
        byte[] attribute = sequence(
                tagged(0x06, OID_COMMON_NAME),
                tagged(0x0C, commonName.getBytes(StandardCharsets.UTF_8)));
        return sequence(tagged(0x31, attribute));
    }

    private static byte[] validity(Date notBefore, Date notAfter) throws IOException {
        return sequence(utcTime(notBefore), utcTime(notAfter));
    }

    /**
     * {@code YYMMDDHHMMSSZ}. Valid until 2049, well past this certificate's ten years.
     *
     * <p>Formatted against {@link Locale#ROOT}, not the default locale. Under a locale whose
     * numbering system is not Latin - Arabic, Bengali and Devanagari among them - {@code %02d}
     * renders native digits, which would put non-ASCII bytes inside a DER UTCTime and produce a
     * certificate nothing can parse. The user's locale has no business reaching the wire format.
     */
    private static byte[] utcTime(Date date) throws IOException {
        Calendar calendar = new GregorianCalendar(TimeZone.getTimeZone("UTC"));
        calendar.setTime(date);
        String text = String.format(Locale.ROOT, "%02d%02d%02d%02d%02d%02dZ",
                calendar.get(Calendar.YEAR) % 100,
                calendar.get(Calendar.MONTH) + 1,
                calendar.get(Calendar.DAY_OF_MONTH),
                calendar.get(Calendar.HOUR_OF_DAY),
                calendar.get(Calendar.MINUTE),
                calendar.get(Calendar.SECOND));
        return tagged(0x17, text.getBytes(StandardCharsets.US_ASCII));
    }

    /** A BIT STRING with no unused trailing bits. */
    private static byte[] bitString(byte[] content) throws IOException {
        byte[] withPadCount = new byte[content.length + 1];
        withPadCount[0] = 0;
        System.arraycopy(content, 0, withPadCount, 1, content.length);
        return tagged(0x03, withPadCount);
    }

    private static byte[] sequence(byte[]... parts) throws IOException {
        ByteArrayOutputStream body = new ByteArrayOutputStream();
        for (byte[] part : parts) {
            body.write(part);
        }
        return tagged(0x30, body.toByteArray());
    }

    /** One DER element: tag, definite length, content. */
    private static byte[] tagged(int tag, byte[] content) throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        out.write(tag);
        int length = content.length;
        if (length < 0x80) {
            out.write(length);
        } else {
            // Long form: the count of length bytes, high bit set, then the length big-endian.
            byte[] lengthBytes = BigInteger.valueOf(length).toByteArray();
            int offset = lengthBytes[0] == 0 ? 1 : 0;
            out.write(0x80 | (lengthBytes.length - offset));
            out.write(lengthBytes, offset, lengthBytes.length - offset);
        }
        out.write(content);
        return out.toByteArray();
    }
}
